# Generated by Django 4.2.15 on 2024-08-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='desccription',
            new_name='description',
        ),
    ]
