# Generated by Django 4.2.15 on 2024-08-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
