# Generated by Django 4.2.15 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='タグ名')),
                ('snippets', models.ManyToManyField(related_name='tags', to='snippets.snippet', verbose_name='スニペット')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
